# Generated by Django 5.2.6 on 2025-09-29 17:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(max_length=255, verbose_name='Nome do grupo')),
                ('moderador', models.CharField(max_length=255, verbose_name='Moderador')),
                ('participantes_anonimos', models.TextField(blank=True, null=True, verbose_name='Participantes anônimos')),
            ],
            options={
                'verbose_name': 'Grupo de Apoio',
                'verbose_name_plural': 'Grupos de Apoio',
            },
        ),
        migrations.CreateModel(
            name='Informativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição do conteúdo informativo')),
                ('tipo_conteudo', models.CharField(max_length=100, verbose_name='Tipo de conteúdo')),
                ('link', models.URLField(max_length=255, verbose_name='Link do conteúdo')),
            ],
            options={
                'verbose_name': 'Informativo',
                'verbose_name_plural': 'Informativos',
            },
        ),
        migrations.CreateModel(
            name='LocalApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do local')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('tipo_local', models.CharField(max_length=100, verbose_name='Tipo de local')),
                ('distancia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distância')),
            ],
            options={
                'verbose_name': 'Local de Apoio',
                'verbose_name_plural': 'Locais de Apoio',
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('consentimento', models.BooleanField(verbose_name='Consentimento para localização')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
            },
        ),
        migrations.CreateModel(
            name='PessoaAnonima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_sessao', models.CharField(max_length=100, unique=True, verbose_name='Identificador da Sessão')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Pessoa Anônima',
                'verbose_name_plural': 'Pessoas Anônimas',
            },
        ),
        migrations.CreateModel(
            name='Voluntaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da voluntária')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('especialidade', models.CharField(max_length=255, verbose_name='Especialidade')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Voluntária',
                'verbose_name_plural': 'Voluntárias',
            },
        ),
        migrations.CreateModel(
            name='Denuncias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da Denúncia')),
                ('tipo_violencia', models.CharField(max_length=100, verbose_name='Tipo de Violência')),
                ('local_aproximado', models.CharField(max_length=200, verbose_name='Local Aproximado')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('tempo_sessao', models.DurationField(blank=True, null=True, verbose_name='Tempo de Sessão')),
                ('identificador_anonimo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pessoaanonima', verbose_name='Identificador Anônimo')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
            },
        ),
        migrations.CreateModel(
            name='ChatApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_mensagem', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Mensagem')),
                ('respondida', models.BooleanField(default=False, verbose_name='Respondida')),
                ('pessoa_anonima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoaanonima', verbose_name='Pessoa Anônima')),
            ],
            options={
                'verbose_name': 'Chat de Apoio',
                'verbose_name_plural': 'Chats de Apoio',
            },
        ),
    ]
