# Generated by Django 5.2.6 on 2025-09-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaSuperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=300, verbose_name='Texto da história')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('status', models.CharField(default='pendente', max_length=20, verbose_name='Status')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de publicação')),
                ('visualizacoes', models.IntegerField(default=0, verbose_name='Visualizações')),
            ],
            options={
                'verbose_name': 'História de Superação',
                'verbose_name_plural': 'Histórias de Superação',
            },
        ),
    ]
