# Generated by Django 5.2.6 on 2025-10-03 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_historiasuperacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatapoio',
            name='pessoa_anonima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pessoaanonima', verbose_name='Pessoa Anônima'),
        ),
    ]
